digital_ecommerce/accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login_page'),
    path('register/', UserRegisterView.as_view(), name='register_page'),
    path('logout/', UserLogoutView.as_view(), name='logout_page'),
    path('reset/', UserPasswordResetView.as_view(), name='password_reset'),
    path('reset/done/', UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('confirm/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('confirm/complete/', UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('activate/<uidb64>/<token>/', ActivateAccount.as_view(), name='activate'),
]

digital_ecommerce/digital_ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('products/', include('products.urls', namespace='products')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

digital_ecommerce/home/urls.py
from django.urls import path
from home.views import *

app_name = 'home'

urlpatterns = [
    path('index_page/', indexconnectview, name='index_page'),
    path('msg_page/', msgconnetcview, name='msg_page'),
]

digital_ecommerce/accounts/models.py
from django.db import models
from .managers import UserManager

# Create your models here.

from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.

class User(AbstractBaseUser):
    email = models.EmailField(max_length=255, unique=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'  # unique must be True #this field is for authenticate by email or username or ...
    objects = UserManager()
    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_lable):
        return True

    @property
    def is_staff(self):
        return self.is_admin
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email_confirmed = models.BooleanField(default=False)

@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
        instance.profile.save()

digital_ecommerce/accounts/forms.py
from django.core.exceptions import ValidationError
from django import forms
from .models import User
from django.contrib.auth.forms import ReadOnlyPasswordHashField


class UserCreationForm(forms.ModelForm):
    password = forms.CharField(label='password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email',)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField(
        help_text="you can change password using <a href=\"../password/\">this form</a>")

    class Meta:
        model = User
        fields = ('email', 'password', 'last_login')

masseges={
    'required':'لطفا ایمیل وارد کنید',
    'invalid':'لطفا ایمیل درست وارد کنید ',

}
masseges1={
    'required':'لطفا کلمه عبور وارد کنید',
}


class RegisterForm(UserCreationForm,forms.Form):
    email = forms.EmailField(label="ادرس ایمیل",
                             widget=forms.EmailInput(attrs={'class': 'form-control _p_dir_ltr', 'type': 'email',
                                                            'placeholder': 'test@gmail.com'}),error_messages=masseges)
    password = forms.CharField(label="کلمه عبور",
                               widget=forms.PasswordInput(attrs=(
                                   {'type': 'password', 'placeholder': 'Password',
                                    'class': 'form-control _p_dir_ltr'})),error_messages=masseges1)
    def clean_email(self):
        email = self.cleaned_data['email']
        user1 = User.objects.filter(email=email).exists()
        if user1:
            raise ValidationError('this email redarly exist')
        return email


class LoginForm(forms.Form):
    email = forms.EmailField(label="ادرس ایمیل",
                             widget=forms.EmailInput(
                                 attrs={'class': 'form-control _p_dir_ltr', 'placeholder': 'test@gmail.com'}))
    password = forms.CharField(label="کلمه عبور", widget=forms.PasswordInput(
        attrs={'class': 'form-control _p_dir_ltr', 'placeholder': 'test@gmail.com'}))

class ResetPasswordForm(forms.Form):
    email = forms.EmailField(label='آدرس ایمیل',)


class PasswordResetConfirmForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())


class PasswordResetForm(forms.Form):
    email = forms.CharField(widget=forms.EmailInput())

digital_ecommerce/accounts/views.py
from django.shortcuts import render, redirect
from django.views import View
from .models import User
from .forms import RegisterForm, LoginForm, PasswordResetForm,PasswordResetConfirmForm
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import views as auth_views
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth import login
from django.conf import settings
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.template.loader import render_to_string
from django.db.models.query_utils import Q
from django.contrib.auth.tokens import default_token_generator
from .tokens import account_activation_token
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str

# Create your views here.

class UserLoginView(View):
    form_class = LoginForm
    template_name = 'accounts/login.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            messages.error(request, 'you already logged in', 'warning')
            return redirect('home:index_page')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        form = self.form_class
        return render(request, 'accounts/login.html', {'form': form})

    def post(self, request):
        if request.method == 'POST':
            form = self.form_class(request.POST)
            if form.is_valid():
                cd = form.cleaned_data
                user = authenticate(request, email=cd['email'], password=cd['password'])
                if user is not None:
                    if user.is_active:
                        login(request, user)
                        messages.success(request, 'احراز هویت با موفقیت انجام شد', 'success')
                        return redirect('home:index_page')
                    else:
                        return messages.error(request, 'حساب غیرفعال است', 'warning')
                else:
                    messages.error(request, 'کاربری با این اطلاعات وجود ندارد', 'warning')
        else:
            form = LoginForm()
        return render(request, 'accounts/login.html', {'form': form})


class UserRegisterView(View):
    form_class = RegisterForm
    template_name = 'accounts/register.html'

    '''def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            messages.error(request, 'you already logged in', 'warning')
            return redirect('home:index_page')
        return super().dispatch(request, *args, **kwargs)'''

    def get(self, request):
        form = self.form_class
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False  # Deactivate account till it is confirmed
            user.save()
            email_send=form.cleaned_data.get('email')

            current_site = get_current_site(request)
            subject = 'Activate Your MySite Account'
            message = render_to_string('accounts/template_activate_account.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
                'protocol': 'https' if request.is_secure() else 'http',
            },)
            send_mail(subject, message,settings.EMAIL_HOST_USER,[email_send], fail_silently=False)


            messages.success(request, ('Please Confirm your email to complete registration.'))

           # return redirect('accounts:login')

        return render(request, self.template_name, {'form': form})
class ActivateAccount(View):

    def get(self, request, uidb64, token, *args, **kwargs):
        try:
            uid = force_str(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and account_activation_token.check_token(user, token):
            user.is_active = True
            user.profile.email_confirmed = True
            user.save()
            login(request, user)
            messages.success(request, ('Your account have been confirmed.'))
            return redirect('home:index_page')
        else:
            messages.warning(request, ('The confirmation link was invalid, possibly because it has already been used.'))
            return redirect('home:index_page')

class UserLogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        messages.success(request, 'logout was successfully', 'success')
        return redirect('home:index_page')


class UserPasswordResetView(View):
    form_class = PasswordResetForm

    def get(self, request):
        form = self.form_class
        return render(request, 'accounts/password-reset.html', {'form': form})

    def post(self, request):
        form = self.form_class
        if request.method == "POST":
            password_reset_form = form(request.POST)
            if password_reset_form.is_valid():
                data = password_reset_form.cleaned_data['email']
                associated_users = User.objects.filter(
                    Q(email=data))  # <QuerySet [<User: amirmohamadzade123@gmail.com>]>
                if associated_users.exists():
                    for user in associated_users:
                        subject = "Password Reset Requested"
                        email_template_name = "accounts/password_reset_email.html"

                        c = {
                            "email": 'digitalecommercewebsite@gmail.com',
                            'domain': 'localhost:8000',
                            'site_name': 'Website',
                            "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                            "user": user,
                            'token': default_token_generator.make_token(user),
                            'protocol': 'http',
                        }
                        email = render_to_string(email_template_name, c)
                        try:
                            send_mail(subject, email, 'admin@example.com', [user.email], fail_silently=False)
                        except BadHeaderError:
                            return HttpResponse('Invalid header found.')
                        return redirect("accounts:password_reset_done")
        password_reset_form = form()
        return render(request=request, template_name="accounts/password-reset.html",
                      context={"form": password_reset_form})


class UserPasswordResetDoneView(auth_views.PasswordResetDoneView):
    template_name = 'accounts/password_reset_done.html'


class UserPasswordResetConfirmView(View):
    form_class = PasswordResetConfirmForm

    def get(self, request, uidb64, token, *args, **kwargs):
        form = self.form_class
        try:
            uid = force_str(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None
        if default_token_generator.check_token(user, token) == True:
            return render(request, 'accounts/password_reset_confirm.html', {'form': form})


        else:
            pass

    def post(self, request, uidb64, token):
        form = self.form_class(request.POST)
        if form.is_valid():
            if form.cleaned_data['password'] == form.cleaned_data['confirm_password']:
                uid = force_str(urlsafe_base64_decode(uidb64))
                user = User.objects.get(pk=uid)
                user.set_password(form.cleaned_data['password'])
                user.save()
                login(request, user)
                return redirect('home:index_page')

            else:
                pass
        return render(request, 'accounts/password_reset_confirm.html', {'form': form})


class UserPasswordResetCompleteView(auth_views.PasswordResetCompleteView):
    template_name = 'accounts/password_reset_complete.html'

digital_ecommerce/accounts/templates/accounts/login.html
{% extends 'home/shared/MainLayot.html' %}
{% load static %}

{% block content %}
<!DOCTYPE html>
<html lang="fa">

<!-- Mirrored from demo.iranlayer.com/bonizkala/login.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 09 Nov 2021 05:55:26 GMT -->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="description" content="متن تست است"/>

    <link rel="apple-touch-icon" sizes="57x57" href="#">
    <link rel="apple-touch-icon" sizes="60x60" href="#">
    <link rel="apple-touch-icon" sizes="72x72" href="#">
    <link rel="apple-touch-icon" sizes="76x76" href="#">
    <link rel="apple-touch-icon" sizes="114x114" href="#">
    <link rel="apple-touch-icon" sizes="120x120" href="#">
    <link rel="apple-touch-icon" sizes="144x144" href="#">
    <link rel="apple-touch-icon" sizes="152x152" href="#">
    <link rel="apple-touch-icon" sizes="180x180" href="#">
    <link rel="icon" type="image/png" sizes="192x192" href="#">
    <link rel="icon" type="image/png" sizes="32x32" href="#">
    <link rel="icon" type="image/png" sizes="96x96" href="#">
    <link rel="icon" type="image/png" sizes="16x16" href="#">

    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="theme-color" content="#ffffff">

    <title>عنوان صفحه</title>
    <link href="{% static 'css/bootstrap3.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/s.css' %}" rel="stylesheet" type="text/css">

</head>
<body>
<div class="_m_search_overlay"></div>

<!-- Header place-->

<div class="_p_mainBody">
    <div class="container">
        <div class="_p_frame _p_small_frame">
            <div class="_m_form_container">
                <div class="_p_outer_title _p_small_title">
                    ورود به بونیز کالا
                </div>
                <div class="_m_form">
                    <form method="POST" action="#">
                        {% csrf_token %}
                        <div class="form-group">
                            <label>{{ form.email.label }}</label>
                            {{ form.email }}
                            <span class="_m_input_error_txt">آدرس ایمیل را وارد کنید</span>
                        </div>
                        <div class="form-group">
                            <label>کلمه عبور</label>
                            <input class="form-control _p_dir_ltr" type="password" name="password" required
                                   placeholder="Password">
                            <span class="_m_input_error_txt">.</span>
                        </div>
                        <div class="_m_remember_form _p_flex_between">
                            <label class="_m_custom_checkbox">مرا به خاطر بسپار
                                <input type="checkbox" name="remember">
                                <span class="checkmark"></span>
                            </label>
                            <a class="_m_recovery_password" href="password-reset.html">بازیابی کلمه عبور</a>
                        </div>
                        <button type="submit" class="_m_btn_block _p_trans _p_orange_color_bg">وارد شوید
                        </button>
                        <div class="_m_login_link">
                            <span>اگر قبلا در بونیز کالا ثبت نام نکرده اید، <a
                                    href="register.html">ثبت نام کنید!</a></span>
                        </div>
                    </form>
                </div>
                <div class="_m_img_form">
                    <span class="icon icon-User"></span>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>

<!-- Footer place-->

<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/vendor.js' %}" defer></script>
<script src="{% static 'js/custom.js' %}" defer></script>

</body>
<!-- Mirrored from demo.iranlayer.com/bonizkala/login.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 09 Nov 2021 05:55:27 GMT -->
</html>
{% endblock %}

digital_ecommerce/accounts/templates/accounts/password-reset.html
{% extends 'home/shared/MainLayot.html' %}
{%  load static %}

{% block content %}
<!DOCTYPE html>
<html lang="fa">

<!-- Mirrored from demo.iranlayer.com/bonizkala/password-reset.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 09 Nov 2021 05:55:36 GMT -->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="description" content="متن تست است"/>

    <link rel="apple-touch-icon" sizes="57x57" href="#">
    <link rel="apple-touch-icon" sizes="60x60" href="#">
    <link rel="apple-touch-icon" sizes="72x72" href="#">
    <link rel="apple-touch-icon" sizes="76x76" href="#">
    <link rel="apple-touch-icon" sizes="114x114" href="#">
    <link rel="apple-touch-icon" sizes="120x120" href="#">
    <link rel="apple-touch-icon" sizes="144x144" href="#">
    <link rel="apple-touch-icon" sizes="152x152" href="#">
    <link rel="apple-touch-icon" sizes="180x180" href="#">
    <link rel="icon" type="image/png" sizes="192x192" href="#">
    <link rel="icon" type="image/png" sizes="32x32" href="#">
    <link rel="icon" type="image/png" sizes="96x96" href="#">
    <link rel="icon" type="image/png" sizes="16x16" href="#">

    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="theme-color" content="#ffffff">

    <title>عنوان صفحه</title>
    <link href="{% static 'css/bootstrap3.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/s.css' %}" rel="stylesheet" type="text/css">

</head>
<body>
<div class="_m_search_overlay"></div>

<!-- Header place -->

<div class="_p_mainBody">
    <div class="container">
        <div class="_p_frame _p_small_frame">
            <div class="_p_outer_title _p_small_title">
                بازیابی کلمه عبور
            </div>
            <div class="_m_form_container">
                <div class="_m_form">
                    <form method="POST" action="#">
                        <input type="hidden" name="_token" value="pGmFuyduoCTwj5e32oPNT88nQQlY3d3EEgH8wElu">
                        <p class="_m_title_forget_pass">
                            برای تغییر و بازیابی کلمه عبور ایمیل خود را وارد نمایید تا ایمیلی حاوی لینک
                            تغییر رمز عبور برای شما ارسال شود.
                        </p>
                        <div class="form-group">

                            <!--<input class="form-control _p_dir_ltr " type="email" name="email" placeholder="ایمیل">-->

                                {% csrf_token %}
                                {{ form.as_p }}


                            <span class="_m_input_error_txt ">آدرس ایمیل را وارد کنید</span>
                        </div>
                        <button type="submit" class="_m_btn_block _p_trans _p_orange_color_bg" value="send">بازیابی کلمه
                            عبور
                        </button>
                    </form>
                </div>
                <div class="_m_img_form">
                    <span class="icon icon-Lock"></span>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>

<!-- Footer place -->

<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/vendor.js' %}" defer></script>
<script src="{% static 'js/custom.js' %}" defer></script>

</body>

<!-- Mirrored from demo.iranlayer.com/bonizkala/password-reset.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 09 Nov 2021 05:55:36 GMT -->
</html>
{% endblock %}

digital_ecommerce/accounts/templates/accounts/password_reset_complete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>StackOverflow</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <style>
        .jumbotron {
            padding: 20px;
            margin-bottom: 20px;
            background-color: #e9ecef;
        }
    </style>
</head>
<body>
<div class="jumbotron">
    <p>your password is changed.</p>
</div>
</body>
</html>

digital_ecommerce/accounts/templates/accounts/password_reset_confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>StackOverflow</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <style>
        .jumbotron {
            padding: 20px;
            margin-bottom: 20px;
            background-color: #e9ecef;
        }
    </style>
</head>
<body>
<div class="jumbotron">

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Change">
    </form>

</div>
</body>
</html>

digital_ecommerce/accounts/templates/accounts/password_reset_done.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>StackOverflow</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <style>
        .jumbotron {
            padding: 20px;
            margin-bottom: 20px;
            background-color: #e9ecef;
        }
    </style>
</head>
<body>
<div class="jumbotron">
    <P>password is send</P>
</div>
</body>
</html>

digital_ecommerce/accounts/templates/accounts/password_reset_email.html
شخصی درخواست بازنشانی رمز عبور شما در فروشگاه را کرده. برای بازنشانی رمز عبور بر روی لینک مقابل کلیک کنید.

{{ protocol}}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

digital_ecommerce/accounts/templates/accounts/password_reset_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>StackOverflow</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <style>
        .jumbotron {
            padding: 20px;
            margin-bottom: 20px;
            background-color: #e9ecef;
        }
    </style>
</head>
<body>
<div class="jumbotron">
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="send">
    </form>
</div>
</body>
</html>

digital_ecommerce/accounts/templates/accounts/register.html
{% extends 'home/shared/MainLayot.html' %}
{% load static %}

{% block content %}
    <!DOCTYPE html>
    <html lang="fa">

    <!-- Mirrored from demo.iranlayer.com/bonizkala/register.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 09 Nov 2021 05:55:27 GMT -->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        <meta name="description" content="متن تست است"/>

        <link rel="apple-touch-icon" sizes="57x57" href="#">
        <link rel="apple-touch-icon" sizes="60x60" href="#">
        <link rel="apple-touch-icon" sizes="72x72" href="#">
        <link rel="apple-touch-icon" sizes="76x76" href="#">
        <link rel="apple-touch-icon" sizes="114x114" href="#">
        <link rel="apple-touch-icon" sizes="120x120" href="#">
        <link rel="apple-touch-icon" sizes="144x144" href="#">
        <link rel="apple-touch-icon" sizes="152x152" href="#">
        <link rel="apple-touch-icon" sizes="180x180" href="#">
        <link rel="icon" type="image/png" sizes="192x192" href="#">
        <link rel="icon" type="image/png" sizes="32x32" href="#">
        <link rel="icon" type="image/png" sizes="96x96" href="#">
        <link rel="icon" type="image/png" sizes="16x16" href="#">

        <meta name="msapplication-TileColor" content="#ffffff">
        <meta name="theme-color" content="#ffffff">

        <title>عنوان صفحه</title>
        <link href="{% static 'css/bootstrap3.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'css/s.css' %}" rel="stylesheet" type="text/css">

    </head>
    <body>
    <div class="_m_search_overlay"></div>

    <!-- Header place -->
    <div class="_p_mainBody">
        <div class="container">
            <div class="_p_frame _p_small_frame">
                <div class="_p_outer_title _p_small_title">
                    ثبت نام
                </div>
                <div class="_m_form_container">
                    <div class="_m_form">
                        <form method="POST" action=" " novalidate >
                            {% csrf_token %}
                            <div class="form-group">
                                <form action="" method="post" >
                                    <div class="form-group" >
                                         {{ form.as_p}}
                                        <span class="_m_input_error_txt">.</span>
                                    </div>
                                    {% csrf_token %}
                            </div>
                            <div class="_m_private">
                                <label class="_m_custom_checkbox"><a href="#"> حریم خصوصی </a> استفاده از سرویس
                                    های سایت بونیز کالا را مطالعه نموده و با کلیه موارد آن موافقم.
                                    <input type="checkbox" name="privacy">
                                    <span class="checkmark"></span>
                                </label>
                                <span class="_m_input_error_txt"></span>
                            </div>
                            <button type="submit" class="_m_btn_block _p_trans _p_green_color_bg" ,value="send">ثبت
                                نام
                            </button>
                            <div class="_m_login_link">
                                <span>اگر قبلا در بونیز کالا ثبت نام کرده اید، <a
                                        href="login.html">وارد شوید!</a></span>
                            </div>
                        </form>
                        </form>
                    </div>
                    <div class="_m_img_form">
                        <span class="icon icon-UserAdd"></span>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div>

    <!-- Footer place -->

    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/vendor.js' %}" defer></script>
    <script src="{% static 'js/custom.js' %}" defer></script>

    </body>

    <!-- Mirrored from demo.iranlayer.com/bonizkala/register.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 09 Nov 2021 05:55:27 GMT -->
    </html>
{% endblock %}

digital_ecommerce/accounts/templates/accounts/template_activate_account.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}
{% endautoescape %}